#!/bin/sh
# Cursor beforeShellExecution hook - blocks risky destructive git commands.
# Source: @blit386/kit (generated by `npx blit agents sync`).

set -u

# python3 is required to parse the JSON payload from Cursor.
# If it is not available the hook exits non-zero so Cursor treats this as a
# fail-closed event and blocks the triggering action rather than silently
# allowing it through.
if ! command -v python3 > /dev/null 2>&1; then
    printf '{"permission":"deny","user_message":"Shell safety hook could not run: python3 is not installed.","agent_message":"python3 is required by the blit shell-safety hook. Install it or run `npx blit agents sync` to regenerate hooks."}\n' >&2
    exit 1
fi

INPUT_JSON="$(cat)"

COMMAND_TEXT="$(printf '%s' "$INPUT_JSON" | python3 -c "
import json, sys

def walk(node):
    if isinstance(node, dict):
        for key in ('command', 'raw_command'):
            value = node.get(key)
            if isinstance(value, str) and value:
                return value
        for value in node.values():
            found = walk(value)
            if found:
                return found
    elif isinstance(node, list):
        for value in node:
            found = walk(value)
            if found:
                return found
    return ''

try:
    data = json.load(sys.stdin)
except Exception:
    print('')
    raise SystemExit(0)

print(walk(data))
")"

if [ -z "$COMMAND_TEXT" ]; then
    printf '{"permission":"allow"}\n'
    exit 0
fi

if printf '%s' "$COMMAND_TEXT" | grep -Eq 'git[[:space:]]+reset[[:space:]]+--hard|git[[:space:]]+clean[[:space:]]+-[^[:cntrl:]]*f|git[[:space:]]+checkout[[:space:]]+--'; then
    printf '{"permission":"deny","user_message":"Blocked a destructive git command that could lose your game changes.","agent_message":"Use safer git operations. Ask the user before discarding any work."}\n'
    exit 0
fi

if printf '%s' "$COMMAND_TEXT" | grep -Eq 'git[[:space:]]+push[^[:cntrl:]]*--force|git[[:space:]]+push[^[:cntrl:]]*-f'; then
    printf '{"permission":"ask","user_message":"Force push detected. Confirm before continuing.","agent_message":"Force push rewrites history. Ask the user for explicit confirmation first."}\n'
    exit 0
fi

printf '{"permission":"allow"}\n'
exit 0
