#!/bin/sh
# Shell safety hook for Cursor (beforeShellExecution) and Claude Code (PreToolUse).
# Blocks risky destructive git commands. Source: @blit386/kit (generated by `npx blit agents sync`).
#
# Protocol:
#   Cursor – JSON on stdout with {"permission":"allow"|"deny"|"ask"}
#   Claude – deny: reason on stderr + exit 2; ask: Claude permissionDecision JSON + exit 0; allow: exit 0
# Detection: Claude stdin includes hook_event_name and/or tool_name.

set -u

# python3 is required to parse the JSON payload from the agent.
# If it is not available the hook exits non-zero so the agent treats this as a
# fail-closed event and blocks the triggering action rather than silently
# allowing it through.
if ! command -v python3 > /dev/null 2>&1; then
    MSG='Shell safety hook could not run: python3 is not installed. Install it or run `npx blit agents sync` to regenerate hooks.'
    # Without python3 we cannot detect the agent. Emit Cursor JSON on stdout (Cursor
    # failClosed) and a stderr reason + exit 2 (Claude PreToolUse block).
    printf '{"permission":"deny","user_message":"%s","agent_message":"%s"}\n' "$MSG" "$MSG"
    printf '%s\n' "$MSG" >&2
    exit 2
fi

INPUT_JSON="$(cat)"

# Detect Claude Code stdin (has hook_event_name or tool_name) vs Cursor.
IS_CLAUDE="$(printf '%s' "$INPUT_JSON" | python3 -c "
import json, sys
try:
    data = json.load(sys.stdin)
except Exception:
    print('0')
    raise SystemExit(0)
print('1' if ('hook_event_name' in data or 'tool_name' in data) else '0')
")"

COMMAND_TEXT="$(printf '%s' "$INPUT_JSON" | python3 -c "
import json, sys

def walk(node):
    if isinstance(node, dict):
        for key in ('command', 'raw_command'):
            value = node.get(key)
            if isinstance(value, str) and value:
                return value
        for value in node.values():
            found = walk(value)
            if found:
                return found
    elif isinstance(node, list):
        for value in node:
            found = walk(value)
            if found:
                return found
    return ''

try:
    data = json.load(sys.stdin)
except Exception:
    print('')
    raise SystemExit(0)

print(walk(data))
")"

respond_allow() {
    if [ "$IS_CLAUDE" = "1" ]; then
        exit 0
    fi
    printf '{"permission":"allow"}\n'
    exit 0
}

respond_deny() {
    USER_MSG="$1"
    AGENT_MSG="$2"
    if [ "$IS_CLAUDE" = "1" ]; then
        # Exit 2 stderr is fed to the model, so use the agent-facing message.
        printf '%s\n' "$AGENT_MSG" >&2
        exit 2
    fi
    printf '{"permission":"deny","user_message":"%s","agent_message":"%s"}\n' "$USER_MSG" "$AGENT_MSG"
    exit 0
}

respond_ask() {
    USER_MSG="$1"
    AGENT_MSG="$2"
    if [ "$IS_CLAUDE" = "1" ]; then
        # permissionDecisionReason for "ask" is shown to the user in the permission UI.
        printf '%s\n' "$USER_MSG" | python3 -c "
import json, sys
reason = sys.stdin.read().rstrip('\n')
print(json.dumps({
    'hookSpecificOutput': {
        'hookEventName': 'PreToolUse',
        'permissionDecision': 'ask',
        'permissionDecisionReason': reason,
    }
}))
"
        exit 0
    fi
    printf '{"permission":"ask","user_message":"%s","agent_message":"%s"}\n' "$USER_MSG" "$AGENT_MSG"
    exit 0
}

if [ -z "$COMMAND_TEXT" ]; then
    respond_allow
fi

if printf '%s' "$COMMAND_TEXT" | grep -Eq 'git[[:space:]]+reset[[:space:]]+--hard|git[[:space:]]+clean[[:space:]]+-[^[:cntrl:]]*f|git[[:space:]]+checkout[[:space:]]+--'; then
    respond_deny \
        'Blocked a destructive git command that could lose your game changes.' \
        'Use safer git operations. Ask the user before discarding any work.'
fi

if printf '%s' "$COMMAND_TEXT" | grep -Eq 'git[[:space:]]+push[^[:cntrl:]]*--force|git[[:space:]]+push[^[:cntrl:]]*-f'; then
    respond_ask \
        'Force push detected. Confirm before continuing.' \
        'Force push rewrites history. Ask the user for explicit confirmation first.'
fi

respond_allow
