/**
 * Turns the templates plus the kit's canonical docs into a ready-to-run game project.
 *
 * Sources:
 *   - ../templates/base  (language-agnostic: index.html, vite config, README, .editorconfig, biome.json)
 *   - ../templates/js    (the JavaScript game + package.json + jsconfig)
 *   - ../templates/optional/* (wizard opt-in: CI, Cursor rules, Claude guide)
 *   - @blit386/kit content (AGENTS.md + docs/) - the single source for the AI/human guidance
 *
 * After emitting all files, scaffold writes `.blit/manifest.json` (the ownership manifest) and
 * `.blit/base/` (pristine copies of kit-owned and shared files) so future `blit agents sync` runs
 * can detect what the user has modified and handle conflicts without clobbering edits.
 */

import { createHash } from 'node:crypto';
import { copyFileSync, cpSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);

/** blit386 version range written into the generated package.json. */
const BLIT386_RANGE = '^1.2.0';

/** Output directory names for optional wizard templates. */
const GITHUB_DIR = '.github';
const CURSOR_DIR = '.cursor';

/** The `.blit` directory name inside every generated project. */
const BLIT_DIR = '.blit';

/**
 * Which agent-sync ownership class a generated file belongs to.
 *
 * - `kit-owned`  – regenerated freely on sync when unmodified; never clobbered when modified
 * - `shared`     – only the managed region (`<!-- blit-kit:managed:start/end -->`) is rewritten on sync
 * - `user-owned` – scaffolded once, never touched again by sync or upgrade
 */
export type FileClass = 'kit-owned' | 'shared' | 'user-owned';

/** One entry in `.blit/manifest.json`. */
export interface ManifestEntry {
    /** File path relative to the project root. */
    path: string;
    /** Ownership class determining how `blit agents sync` handles this file. */
    class: FileClass;
    /** Kit version that last wrote this file. */
    kitVersion: string;
    /** SHA-256 hex digest of the file content as generated (before any user edits). */
    sha256: string;
}

/** The full `.blit/manifest.json` structure. */
export interface BlitManifest {
    /** Kit version that created this project. */
    kitVersion: string;
    /** ISO-8601 creation timestamp. */
    createdAt: string;
    /**
     * Template variables used at scaffold time (package-manager commands, project name, ...).
     * `blit agents sync` reads these back so it regenerates kit files with the exact same values,
     * independent of the environment it runs in.
     */
    vars: Record<string, string>;
    /** One entry per generated file, sorted by path for stable diffs. */
    files: ManifestEntry[];
}

/**
 * Classify a generated file by its path relative to the project root.
 *
 * Files under `docs/` and AI-tooling directories are kit-owned (sync regenerates them).
 * `AGENTS.md` and `CLAUDE.md` are shared (sync rewrites only the managed region).
 * Everything else is user-owned (scaffold once, never overwritten by sync or upgrade).
 */
function classifyFile(relPath: string): FileClass {
    const normalized = relPath.replace(/\\/g, '/');

    // AGENTS.md and CLAUDE.md carry managed-region markers; only those regions are rewritten on sync.
    if (normalized === 'AGENTS.md' || normalized === 'CLAUDE.md') {
        return 'shared';
    }

    // Docs and generated AI-tooling files are regenerated by sync.
    if (
        normalized.startsWith('docs/') ||
        normalized.startsWith('.cursor/rules/') ||
        normalized.startsWith('.cursor/hooks/') ||
        normalized.startsWith('.cursor/commands/') ||
        normalized === '.cursor/hooks.json' ||
        normalized.startsWith('.claude/skills/') ||
        normalized.startsWith('.claude/rules/') ||
        normalized === '.claude/settings.json'
    ) {
        return 'kit-owned';
    }

    // Source files, language config (jsconfig.json, tsconfig.json), README, package.json – the user owns these.
    return 'user-owned';
}

export type AgentChoice = 'none' | 'claude' | 'cursor';

/** Which language layer to scaffold. */
export type LanguageChoice = 'js' | 'ts';

export interface ScaffoldOptions {
    targetDir: string;
    projectName: string;
    pmInstall: string;
    pmRunDev: string;
    pmRunBuild: string;
    pmRunFormat: string;
    pmRunLint: string;
    includeCi?: boolean;
    agent?: AgentChoice;
    /** Language layer to use; defaults to `'js'`. */
    language?: LanguageChoice;
}

type TemplateVars = Record<string, string>;

function templatesDir(): string {
    // dist/index.js -> ../templates (templates ships alongside dist in the published package).
    return fileURLToPath(new URL('../templates', import.meta.url));
}

function kitRoot(): string {
    return dirname(require.resolve('@blit386/kit/package.json'));
}

function kitVersionRange(): string {
    const pkg = JSON.parse(readFileSync(join(kitRoot(), 'package.json'), 'utf8')) as { version?: string };
    return pkg.version ? `^${pkg.version}` : '^0.1.0';
}

/** Replace {{placeholder}} tokens; unknown tokens are left untouched so mistakes are visible. */
function render(content: string, vars: TemplateVars): string {
    return content.replace(/\{\{(\w+)\}\}/g, (_match, key: string) => vars[key] ?? `{{${key}}}`);
}

function stripTmpl(name: string): string {
    return name.endsWith('.tmpl') ? name.slice(0, -'.tmpl'.length) : name;
}

/** Map template file/dir names to their output names in the generated project. */
function mapOutputName(name: string): string {
    if (name === 'gitignore') {
        return '.gitignore';
    }
    if (name === 'editorconfig') {
        return '.editorconfig';
    }
    if (name === 'dot-cursor') {
        return CURSOR_DIR;
    }
    if (name === 'dot-github') {
        return GITHUB_DIR;
    }
    return stripTmpl(name);
}

/** Turn a folder name into a valid npm package name (lowercase, dashes, no surprises). */
function toPackageName(name: string): string {
    const cleaned = name
        .toLowerCase()
        .replace(/[^a-z0-9-]+/g, '-')
        .replace(/^-+|-+$/g, '');
    return cleaned.length > 0 ? cleaned : 'my-blit-game';
}

/** Copy a template tree, renaming special files/dirs, stripping `.tmpl`, and rendering placeholders. */
function copyTemplateTree(srcDir: string, destDir: string, vars: TemplateVars, written?: Set<string>): void {
    mkdirSync(destDir, { recursive: true });

    for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
        const srcPath = join(srcDir, entry.name);
        const outName = mapOutputName(entry.name);
        const destPath = join(destDir, outName);

        if (entry.isDirectory()) {
            copyTemplateTree(srcPath, destPath, vars, written);
        } else {
            const content = readFileSync(srcPath, 'utf8');
            writeFileSync(destPath, render(content, vars));
            written?.add(destPath);
        }
    }
}

/** Compute the SHA-256 hex digest of a UTF-8 file. */
function sha256(filePath: string): string {
    return createHash('sha256').update(readFileSync(filePath)).digest('hex');
}

/**
 * Write `.blit/manifest.json` recording every generated file's path, class, kit version, and hash.
 * Also write pristine copies of kit-owned and shared files under `.blit/base/` so a future
 * `blit agents sync` run can perform a proper three-way merge instead of clobbering user edits.
 */
function writeBlitManifest(targetDir: string, writtenPaths: Set<string>, kitVer: string, vars: TemplateVars): void {
    const blitDir = join(targetDir, BLIT_DIR);
    const baseDir = join(blitDir, 'base');
    mkdirSync(baseDir, { recursive: true });

    const entries: ManifestEntry[] = [];

    for (const absPath of writtenPaths) {
        const relPath = relative(targetDir, absPath).replace(/\\/g, '/');

        // Skip files that are inside .blit/ itself (manifest and base copies).
        if (relPath.startsWith('.blit/')) {
            continue;
        }

        const fileClass = classifyFile(relPath);
        const digest = sha256(absPath);

        entries.push({ path: relPath, class: fileClass, kitVersion: kitVer, sha256: digest });

        // Keep a pristine copy for future three-way merges (kit-owned and shared files only).
        if (fileClass === 'kit-owned' || fileClass === 'shared') {
            const baseCopyPath = join(baseDir, relPath);
            mkdirSync(dirname(baseCopyPath), { recursive: true });
            copyFileSync(absPath, baseCopyPath);
        }
    }

    // Sort by path for a stable, human-readable manifest.
    entries.sort((a, b) => a.path.localeCompare(b.path));

    const manifest: BlitManifest = {
        kitVersion: kitVer,
        createdAt: new Date().toISOString(),
        vars,
        files: entries,
    };

    writeFileSync(join(blitDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
}

/**
 * Strip YAML frontmatter (a `---`…`---` block at the top) from a markdown file.
 *
 * Kit rules carry frontmatter used by the Cursor adapter (alwaysApply, globs). The Claude adapter uses
 * only the body, so it strips the frontmatter before emitting the file into `.claude/rules/`.
 */
function stripFrontmatter(content: string): string {
    if (!content.startsWith('---')) {
        return content;
    }

    const firstLineEnd = content.indexOf('\n');
    if (firstLineEnd === -1) {
        return content;
    }

    // Closing delimiter must be alone on a line; YAML values may contain `---` inline.
    const rest = content.slice(firstLineEnd + 1);
    const closingMatch = rest.match(/^---\s*(?:\r?\n|$)/m);
    if (!closingMatch || closingMatch.index === undefined) {
        return content;
    }

    const bodyStart = firstLineEnd + 1 + closingMatch.index + closingMatch[0].length;

    return content.slice(bodyStart).replace(/^\r?\n/, '');
}

/**
 * Extract the content between `<!-- blit-kit:managed:start -->` and `<!-- blit-kit:managed:end -->` markers,
 * skipping the ownership-comment block that immediately follows the start marker.
 */
function extractManagedRegion(content: string): string {
    const START = '<!-- blit-kit:managed:start -->';
    const END = '<!-- blit-kit:managed:end -->';

    const startIdx = content.indexOf(START);
    const endIdx = content.indexOf(END);

    if (startIdx === -1 || endIdx === -1) {
        return content.trim();
    }

    // Skip the start marker itself.
    let bodyStart = startIdx + START.length;

    // If an HTML comment immediately follows (the kit ownership note), skip past it.
    const afterStart = content.slice(bodyStart).trimStart();
    if (afterStart.startsWith('<!--')) {
        const commentEnd = content.indexOf('-->', bodyStart);
        if (commentEnd !== -1) {
            bodyStart = commentEnd + '-->'.length;
        }
    }

    return content.slice(bodyStart, endIdx).trim();
}

/**
 * Generate the Claude Code adapter files from the kit's canonical IR:
 *   - `CLAUDE.md`                        (shared file with a managed region)
 *   - `.claude/rules/{name}.md`          (kit-owned, one per rule in content/rules/)
 *   - `.claude/skills/{name}/SKILL.md`   (kit-owned, one per skill in content/skills/)
 *
 * Replaces the static `templates/optional/claude/CLAUDE.md.tmpl`. The generator reads the kit content
 * and composes per-agent output, applying template-variable substitution throughout.
 */
function generateClaudeAdapter(
    kitContentRoot: string,
    targetDir: string,
    vars: TemplateVars,
    writtenPaths: Set<string>,
): void {
    const contentRoot = join(kitContentRoot, 'content');

    // Build CLAUDE.md: managed region = AGENTS.md body + project commands.
    const agentsMd = readFileSync(join(contentRoot, 'AGENTS.md'), 'utf8');
    const managedBody = extractManagedRegion(agentsMd);

    const commandsBlock = [
        '',
        '## Commands',
        '',
        `- \`${vars.pmRunDev}\` - start the dev server`,
        `- \`${vars.pmRunBuild}\` - build for production`,
        `- \`${vars.pmRunFormat}\` - format the code`,
        `- \`${vars.pmRunLint}\` - check code style`,
        '- `npx blit doctor` - check your setup',
        '- `npx blit upgrade` - update BLIT386',
    ].join('\n');

    const claudeMd = [
        '<!-- blit-kit:managed:start -->',
        '<!-- This block is managed by @blit386/kit. Run `npx blit agents sync` to update it. Put your own notes below the end marker. -->',
        '',
        managedBody,
        commandsBlock,
        '',
        '<!-- blit-kit:managed:end -->',
        '',
        '## Your notes',
        '',
        'Add project-specific notes for Claude here. This section is yours.',
        '',
    ].join('\n');

    const claudePath = join(targetDir, 'CLAUDE.md');
    writeFileSync(claudePath, claudeMd);
    writtenPaths.add(claudePath);

    // Emit .claude/rules/ from content/rules/*.md (strip frontmatter; Claude reads plain markdown).
    const rulesDir = join(contentRoot, 'rules');
    if (existsSync(rulesDir)) {
        const claudeRulesDir = join(targetDir, '.claude', 'rules');
        mkdirSync(claudeRulesDir, { recursive: true });

        for (const entry of readdirSync(rulesDir, { withFileTypes: true })) {
            if (!entry.isFile() || !entry.name.endsWith('.md')) {
                continue;
            }

            const src = join(rulesDir, entry.name);
            const dest = join(claudeRulesDir, entry.name);
            writeFileSync(dest, render(stripFrontmatter(readFileSync(src, 'utf8')), vars));
            writtenPaths.add(dest);
        }
    }

    // Emit .claude/skills/ from content/skills/*/SKILL.md. The frontmatter is kept
    // verbatim: Claude Code reads name/description from it to discover and trigger
    // the skill, so stripping it would make the skill inert.
    const skillsDir = join(contentRoot, 'skills');
    if (existsSync(skillsDir)) {
        for (const entry of readdirSync(skillsDir, { withFileTypes: true })) {
            if (!entry.isDirectory()) {
                continue;
            }

            const skillSrc = join(skillsDir, entry.name, 'SKILL.md');
            if (!existsSync(skillSrc)) {
                continue;
            }

            const skillDestDir = join(targetDir, '.claude', 'skills', entry.name);
            mkdirSync(skillDestDir, { recursive: true });
            const dest = join(skillDestDir, 'SKILL.md');
            writeFileSync(dest, render(readFileSync(skillSrc, 'utf8'), vars));
            writtenPaths.add(dest);
        }
    }
}

// ---------------------------------------------------------------------------
// Cursor adapter types (mirrors the Cursor hooks.json wire format)
// ---------------------------------------------------------------------------

interface CursorHookEntry {
    /** Shell command to run for this hook event. */
    command?: string;
    /** Regex string used by Cursor to match which tool calls trigger this hook. */
    matcher?: string;
    /** Seconds before the hook is considered timed out. */
    timeout?: number;
    /** When true, Cursor blocks the triggering action if the hook fails or exits non-zero. */
    failClosed?: boolean;
}

interface CursorHooksJson {
    version: number;
    hooks: Record<string, CursorHookEntry[]>;
}

// ---------------------------------------------------------------------------
// Hooks-manifest types (canonical intent format in content/hooks.manifest.json)
// ---------------------------------------------------------------------------

interface HookManifestCursorBlock extends CursorHookEntry {
    /** Cursor hook event: "afterFileEdit" | "beforeShellExecution" | "preToolUse" */
    event: string;
}

interface HookManifestEntry {
    /** Stable identifier. */
    id: string;
    /** Human-readable intent used in AGENTS.md prose and as documentation. */
    intent: string;
    /** Cursor-specific rendering of this hook. */
    cursor?: HookManifestCursorBlock;
}

interface HooksManifest {
    version: string;
    hooks: HookManifestEntry[];
}

/** Translate the canonical hooks manifest into Cursor's `hooks.json` structure, rendering template vars. */
function buildCursorHooks(manifest: HooksManifest, vars: TemplateVars): CursorHooksJson {
    const hooks: Record<string, CursorHookEntry[]> = {};

    for (const hook of manifest.hooks) {
        if (!hook.cursor) {
            continue;
        }

        const { event, ...rest } = hook.cursor;
        const entry: CursorHookEntry = {};

        if (rest.command !== undefined) {
            entry.command = render(rest.command, vars);
        }

        if (rest.matcher !== undefined) {
            entry.matcher = rest.matcher;
        }

        if (rest.timeout !== undefined) {
            entry.timeout = rest.timeout;
        }

        if (rest.failClosed !== undefined) {
            entry.failClosed = rest.failClosed;
        }

        if (!hooks[event]) {
            hooks[event] = [];
        }

        hooks[event].push(entry);
    }

    return { version: 1, hooks };
}

/**
 * Generate the Cursor adapter files from the kit's canonical IR:
 *   - `.cursor/rules/{name}.mdc`          (kit-owned, MDC format; frontmatter from rule files)
 *   - `.cursor/hooks.json`                (kit-owned; translated from content/hooks.manifest.json)
 *   - `.cursor/hooks/shell-safety.sh`     (kit-owned; shell hook script)
 *   - `.cursor/commands/{name}.md`        (kit-owned, one per skill in content/skills/)
 *
 * Replaces the static `templates/optional/cursor/` tree.
 */
function generateCursorAdapter(
    kitContentRoot: string,
    targetDir: string,
    vars: TemplateVars,
    writtenPaths: Set<string>,
): void {
    const contentRoot = join(kitContentRoot, 'content');
    const cursorDir = join(targetDir, CURSOR_DIR);
    mkdirSync(cursorDir, { recursive: true });

    // Emit .cursor/rules/*.mdc from content/rules/*.md.
    // Kit rules carry YAML frontmatter with description/alwaysApply/globs — Cursor reads this as MDC.
    const rulesDir = join(contentRoot, 'rules');
    if (existsSync(rulesDir)) {
        const cursorRulesDir = join(cursorDir, 'rules');
        mkdirSync(cursorRulesDir, { recursive: true });

        for (const entry of readdirSync(rulesDir, { withFileTypes: true })) {
            if (!entry.isFile() || !entry.name.endsWith('.md')) {
                continue;
            }

            const src = join(rulesDir, entry.name);
            const destName = entry.name.replace(/\.md$/, '.mdc');
            const dest = join(cursorRulesDir, destName);
            writeFileSync(dest, render(readFileSync(src, 'utf8'), vars));
            writtenPaths.add(dest);
        }
    }

    // Emit .cursor/hooks.json from content/hooks.manifest.json.
    const hookManifestPath = join(contentRoot, 'hooks.manifest.json');
    if (existsSync(hookManifestPath)) {
        const manifest = JSON.parse(readFileSync(hookManifestPath, 'utf8')) as HooksManifest;
        const cursorHooks = buildCursorHooks(manifest, vars);

        const hooksJsonPath = join(cursorDir, 'hooks.json');
        writeFileSync(hooksJsonPath, `${JSON.stringify(cursorHooks, null, 2)}\n`);
        writtenPaths.add(hooksJsonPath);
    }

    // Copy hook scripts referenced in the manifest (e.g. shell-safety.sh).
    const hooksScriptsDir = join(contentRoot, 'hooks');
    if (existsSync(hooksScriptsDir)) {
        const cursorHooksDir = join(cursorDir, 'hooks');
        mkdirSync(cursorHooksDir, { recursive: true });

        for (const entry of readdirSync(hooksScriptsDir, { withFileTypes: true })) {
            if (!entry.isFile()) {
                continue;
            }

            const src = join(hooksScriptsDir, entry.name);
            const dest = join(cursorHooksDir, entry.name);
            writeFileSync(dest, readFileSync(src, 'utf8'));
            writtenPaths.add(dest);
        }
    }

    // Emit .cursor/commands/ from content/skills/*/SKILL.md.
    const skillsDir = join(contentRoot, 'skills');
    if (existsSync(skillsDir)) {
        const commandsDir = join(cursorDir, 'commands');
        mkdirSync(commandsDir, { recursive: true });

        for (const entry of readdirSync(skillsDir, { withFileTypes: true })) {
            if (!entry.isDirectory()) {
                continue;
            }

            const skillSrc = join(skillsDir, entry.name, 'SKILL.md');
            if (!existsSync(skillSrc)) {
                continue;
            }

            // Strip the skill's YAML frontmatter: a Cursor command is invoked by
            // filename, so name/description add no value and would render as literal
            // text. The Claude adapter keeps the frontmatter (a skill needs it).
            const dest = join(commandsDir, `${entry.name}.md`);
            writeFileSync(dest, render(stripFrontmatter(readFileSync(skillSrc, 'utf8')), vars));
            writtenPaths.add(dest);
        }
    }
}

/** Generate the project at `targetDir`. The caller guarantees the folder is empty. */
export function scaffold(options: ScaffoldOptions): void {
    // Resolve the actual kit version string (not the range) for the manifest.
    const kitPkg = JSON.parse(readFileSync(join(kitRoot(), 'package.json'), 'utf8')) as { version?: string };
    const kitVer = kitPkg.version ?? '0.1.0';

    const language: LanguageChoice = options.language ?? 'js';

    // gameFile is the user-readable path (README); entryFile is the HTML script src (leading slash).
    const gameFile = language === 'ts' ? 'src/game.ts' : 'src/game.js';
    const entryFile = `/${gameFile}`;

    const vars: TemplateVars = {
        projectName: options.projectName,
        packageName: toPackageName(options.projectName),
        blit386Version: BLIT386_RANGE,
        kitVersion: kitVersionRange(),
        pmInstall: options.pmInstall,
        pmRunDev: options.pmRunDev,
        pmRunBuild: options.pmRunBuild,
        pmRunFormat: options.pmRunFormat,
        pmRunLint: options.pmRunLint,
        // Resolved per language so base templates stay language-agnostic.
        entryFile,
        gameFile,
    };

    // Collect every file path we write so we can build the ownership manifest.
    const writtenPaths = new Set<string>();

    const templates = templatesDir();
    copyTemplateTree(join(templates, 'base'), options.targetDir, vars, writtenPaths);
    copyTemplateTree(join(templates, language), options.targetDir, vars, writtenPaths);

    if (options.includeCi) {
        copyTemplateTree(
            join(templates, 'optional', 'ci', 'github'),
            join(options.targetDir, GITHUB_DIR),
            vars,
            writtenPaths,
        );
    }

    if (options.agent === 'cursor') {
        generateCursorAdapter(kitRoot(), options.targetDir, vars, writtenPaths);
    }

    if (options.agent === 'claude') {
        generateClaudeAdapter(kitRoot(), options.targetDir, vars, writtenPaths);
    }

    // Copy the kit's canonical guidance (single source of truth for AGENTS.md + docs).
    const content = kitRoot();
    const agentsPath = join(options.targetDir, 'AGENTS.md');
    copyFileSync(join(content, 'content', 'AGENTS.md'), agentsPath);
    writtenPaths.add(agentsPath);

    const docsDestDir = join(options.targetDir, 'docs');
    cpSync(join(content, 'content', 'docs'), docsDestDir, { recursive: true });

    // cpSync does not tell us what it copied, so scan the written docs tree.
    collectTree(docsDestDir, writtenPaths);

    // Seal the ownership manifest and write pristine base copies.
    writeBlitManifest(options.targetDir, writtenPaths, kitVer, vars);
}

/** Recursively add all files under `dir` to `collected` (used after cpSync which returns void). */
function collectTree(dir: string, collected: Set<string>): void {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const fullPath = join(dir, entry.name);

        if (entry.isDirectory()) {
            collectTree(fullPath, collected);
        } else {
            collected.add(fullPath);
        }
    }
}
